// <auto-generated />
using EllevationDataImport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EllevationDataInport.Migrations
{
    [DbContext(typeof(DataImportContext))]
    partial class DataImportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("EllevationDataImport.GenderCodes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EllevationGenderCode");

                    b.Property<string>("SisGenderName");

                    b.HasKey("ID");

                    b.ToTable("GenderCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
